POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Homework",
    "author": "Pepepopo",
    "url": "https://fullstackopen.com/en/part5/login_in_frontend#handling-login",
    "likes": 0
}